apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: chatapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/tnxq/mongo-data
  storageClassName: local-storage